# 第二次作业

## 第一题

In [1]:

import numpy as np
arr = np.arange(1, 13).reshape(3, 4)
print("数组维度（ndim）：", arr.ndim)
print("数组形状（shape）：", arr.shape)
print("元素总个数（size）：", arr.size)


数组维度（ndim）： 2
数组形状（shape）： (3, 4)
元素总个数（size）： 12


## 第二题

In [2]:

import numpy as np
float_arr = np.array([1.5, 2.6, 3.7, 4.8])
print("转换前数组：", float_arr)
print("转换前数据类型：", float_arr.dtype.name)
int_arr = float_arr.astype(np.int32)
print("转换后数组：", int_arr)
print("转换后数据类型：", int_arr.dtype.name)

转换前数组： [1.5 2.6 3.7 4.8]
转换前数据类型： float64
转换后数组： [1 2 3 4]
转换后数据类型： int32


## 第三题

In [3]:

import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
sub_arr = arr[:2, 1:3]
print("切片结果：", sub_arr)

切片结果： [[2 3]
 [6 7]]


## 第四题

In [4]:

import numpy as np
arr = np.array([10, 15, 20, 25, 30, 35])
fancy_index = arr[[0, 2, 4]]
print("花式索引结果：", fancy_index)
bool_index = arr[arr > 20]
print("布尔索引结果：", bool_index)

花式索引结果： [10 20 30]
布尔索引结果： [25 30 35]


## 第五题

In [5]:

import numpy as np
arr_a = np.zeros((3, 4))
arr_b = np.array([1, 2, 3, 4])
result = arr_a + arr_b
print("广播相加结果：\n", result)

广播相加结果：
 [[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


## 第六题

In [6]:

import numpy as np
x = np.array([1, 4, 9, 16])
y = np.array([2, 1, 4, 5])
sqrt_x = np.sqrt(x)
print("x的平方根：", sqrt_x)
max_result = np.maximum(sqrt_x, y)
print("对应位置最大值：", max_result)

x的平方根： [1. 2. 3. 4.]
对应位置最大值： [2. 2. 4. 5.]


## 第七题

In [7]:

import numpy as np
arr = np.arange(24).reshape((2, 3, 4))
transposed_arr = arr.transpose((1, 0, 2))
print("转置后数组形状：", transposed_arr.shape)

转置后数组形状： (3, 2, 4)


## 第八题

In [8]:

import numpy as np
arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])
arr_con = np.array([True, False, True])
where_result = np.where(arr_con, arr_x, arr_y)
print("条件选择结果：", where_result)

条件选择结果： [1 6 7]


## 第九题

In [9]:

import numpy as np
arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])
mean_val = arr.mean()
print("数组算术平均值：", mean_val)
arr.sort(axis=0)
print("按列排序后的数组：\n", arr)


数组算术平均值： 3.888888888888889
按列排序后的数组：
 [[3 2 2]
 [4 3 2]
 [6 6 7]]


## 第十题

In [10]:

import numpy as np
np.random.seed(10)
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)
print("矩阵A：\n", A)
print("矩阵B：\n", B)
dot_result = np.dot(A, B)
print("矩阵点积结果：\n", dot_result)

矩阵A：
 [[0.77132064 0.02075195]
 [0.63364823 0.74880388]]
矩阵B：
 [[0.49850701 0.22479665]
 [0.19806286 0.76053071]]
矩阵点积结果：
 [[0.38861894 0.18917279]
 [0.46418833 0.71193035]]
